package stargatetech2.api.stargate;

public enum DialError{
	SOURCE_ADDRESS_NOT_FOUND,
	TARGET_ADDRESS_NOT_FOUND,
	SOURCE_WORLD_NOT_FOUND,
	TARGET_WORLD_NOT_FOUND,
	CANNOT_DIAL_SAME_WORLD,
	FAILED_CHUNKLOADING_SOURCE,
	FAILED_CHUNKLOADING_TARGET,
	SOURCE_GATE_NOT_FOUND,
	TARGET_GATE_NOT_FOUND,
	SOURCE_GATE_UNABLE_TO_DIAL,
	TARGET_GATE_BUSY;
}
